/**
 * 東京23区 住みやすさ分析・マップ用マスターデータ
 * 
 * - x, y: 23区完成マップ上のパーセント位置 (0~100)
 * - xScatter, yScatter: スクロール前（散らばり時）の初期パーセント位置
 * - 各種スコア: 100点満点の評価値
 */

export const districtsData = [
  {
    code: '13101',
    name: '千代田区',
    x: 50,
    y: 48,
    xScatter: 15,
    yScatter: 85,
    bestEmoji: '🏛️',
    description: '皇居を擁する日本の中心。治安と防災基盤の強さがトップクラス。',
    scores: {
      childcare: 88,
      park: 82,
      disaster: 96,
      crime: 92,
      transit: 98,
      shopping: 85,
      medical: 95,
      cost: 40,
      quietness: 78,
    },
  },
  {
    code: '13102',
    name: '中央区',
    x: 58,
    y: 52,
    xScatter: 88,
    yScatter: 90,
    bestEmoji: '🏬',
    description: '銀座・日本橋の商業力と湾岸エリアの先進性が融合した街。',
    scores: {
      childcare: 85,
      park: 70,
      disaster: 88,
      crime: 85,
      transit: 96,
      shopping: 98,
      medical: 90,
      cost: 42,
      quietness: 68,
    },
  },
  {
    code: '13103',
    name: '港区',
    x: 48,
    y: 60,
    xScatter: 10,
    yScatter: 65,
    bestEmoji: '🗼',
    description: '国際性・医療・商業機能が究極水準。洗練された都心ライフ。',
    scores: {
      childcare: 90,
      park: 80,
      disaster: 85,
      crime: 82,
      transit: 95,
      shopping: 96,
      medical: 98,
      cost: 30,
      quietness: 65,
    },
  },
  {
    code: '13104',
    name: '新宿区',
    x: 40,
    y: 44,
    xScatter: 82,
    yScatter: 12,
    bestEmoji: '🌃',
    description: 'ターミナル駅の利便性と豊かな新宿御苑の緑が同居。',
    scores: {
      childcare: 78,
      park: 78,
      disaster: 80,
      crime: 70,
      transit: 100,
      shopping: 98,
      medical: 92,
      cost: 50,
      quietness: 55,
    },
  },
  {
    code: '13105',
    name: '文京区',
    x: 48,
    y: 38,
    xScatter: 30,
    yScatter: 10,
    bestEmoji: '🎓',
    description: '文教地区として知られ、23区屈指の治安の良さと教育環境。',
    scores: {
      childcare: 95,
      park: 85,
      disaster: 88,
      crime: 98,
      transit: 88,
      shopping: 75,
      medical: 96,
      cost: 58,
      quietness: 92,
    },
  },
  {
    code: '13106',
    name: '台東区',
    x: 60,
    y: 38,
    xScatter: 92,
    yScatter: 25,
    bestEmoji: '🏮',
    description: '浅草・上野を擁する江戸情緒と現代利便性が共存する街。',
    scores: {
      childcare: 80,
      park: 82,
      disaster: 76,
      crime: 75,
      transit: 92,
      shopping: 90,
      medical: 85,
      cost: 65,
      quietness: 68,
    },
  },
  {
    code: '13107',
    name: '墨田区',
    x: 68,
    y: 40,
    xScatter: 95,
    yScatter: 42,
    bestEmoji: '🗼',
    description: 'スカイツリーのある新旧魅力の街。子育て支援が手厚い。',
    scores: {
      childcare: 88,
      park: 80,
      disaster: 75,
      crime: 82,
      transit: 86,
      shopping: 88,
      medical: 80,
      cost: 72,
      quietness: 75,
    },
  },
  {
    code: '13108',
    name: '江東区',
    x: 68,
    y: 58,
    xScatter: 90,
    yScatter: 78,
    bestEmoji: '🌉',
    description: '豊洲・有明などファミリーに絶大な人気を誇る大型商業＆公園都市。',
    scores: {
      childcare: 92,
      park: 92,
      disaster: 80,
      crime: 84,
      transit: 88,
      shopping: 92,
      medical: 86,
      cost: 60,
      quietness: 76,
    },
  },
  {
    code: '13109',
    name: '品川区',
    x: 50,
    y: 70,
    xScatter: 60,
    yScatter: 95,
    bestEmoji: '🚄',
    description: '新幹線・羽田アクセス抜群。小中一貫教育など独自の教育革新。',
    scores: {
      childcare: 94,
      park: 82,
      disaster: 82,
      crime: 86,
      transit: 96,
      shopping: 88,
      medical: 88,
      cost: 52,
      quietness: 78,
    },
  },
  {
    code: '13110',
    name: '目黒区',
    x: 38,
    y: 66,
    xScatter: 18,
    yScatter: 78,
    bestEmoji: '🌸',
    description: '目黒川の桜並木や自由が丘に代表される洗練された閑静な高級住宅街。',
    scores: {
      childcare: 89,
      park: 86,
      disaster: 85,
      crime: 90,
      transit: 88,
      shopping: 86,
      medical: 86,
      cost: 45,
      quietness: 88,
    },
  },
  {
    code: '13111',
    name: '大田区',
    x: 48,
    y: 84,
    xScatter: 38,
    yScatter: 98,
    bestEmoji: '✈️',
    description: '羽田空港を擁する23区最大の面積。多摩川沿いの自然と町工場の活気。',
    scores: {
      childcare: 86,
      park: 90,
      disaster: 80,
      crime: 82,
      transit: 86,
      shopping: 82,
      medical: 82,
      cost: 70,
      quietness: 80,
    },
  },
  {
    code: '13112',
    name: '世田谷区',
    x: 24,
    y: 66,
    xScatter: 5,
    yScatter: 50,
    bestEmoji: '🌳',
    description: '緑豊かな自然と閑静な住環境。圧倒的な人口と子育て世帯の支持。',
    scores: {
      childcare: 92,
      park: 96,
      disaster: 82,
      crime: 88,
      transit: 82,
      shopping: 84,
      medical: 88,
      cost: 58,
      quietness: 90,
    },
  },
  {
    code: '13113',
    name: '渋谷区',
    x: 40,
    y: 55,
    xScatter: 12,
    yScatter: 35,
    bestEmoji: '🎨',
    description: 'トレンドの発信地でありつつ、代々木公園や恵比寿など豊かな住環境も。',
    scores: {
      childcare: 86,
      park: 88,
      disaster: 82,
      crime: 72,
      transit: 98,
      shopping: 100,
      medical: 90,
      cost: 35,
      quietness: 60,
    },
  },
  {
    code: '13114',
    name: '中野区',
    x: 32,
    y: 42,
    xScatter: 8,
    yScatter: 22,
    bestEmoji: '🛍️',
    description: '新宿へのアクセス抜群。商店街が充実しコスパに優れる住みやすい街。',
    scores: {
      childcare: 84,
      park: 76,
      disaster: 78,
      crime: 80,
      transit: 92,
      shopping: 90,
      medical: 82,
      cost: 72,
      quietness: 74,
    },
  },
  {
    code: '13115',
    name: '杉並区',
    x: 20,
    y: 44,
    xScatter: 2,
    yScatter: 15,
    bestEmoji: '☕',
    description: '高円寺・阿佐ヶ谷・荻窪などカルチャーと落ち着いた住環境が融合。',
    scores: {
      childcare: 90,
      park: 88,
      disaster: 82,
      crime: 88,
      transit: 84,
      shopping: 86,
      medical: 84,
      cost: 68,
      quietness: 88,
    },
  },
  {
    code: '13116',
    name: '豊島区',
    x: 42,
    y: 32,
    xScatter: 22,
    yScatter: 5,
    bestEmoji: '🦉',
    description: '池袋を中心に文化都市として劇的進化。消滅可能性都市からの劇的脱却。',
    scores: {
      childcare: 90,
      park: 80,
      disaster: 80,
      crime: 74,
      transit: 96,
      shopping: 96,
      medical: 88,
      cost: 68,
      quietness: 66,
    },
  },
  {
    code: '13117',
    name: '北区',
    x: 50,
    y: 22,
    xScatter: 48,
    yScatter: 2,
    bestEmoji: '🚂',
    description: '赤羽・王子など交通の要所。親しみやすい商店街と高いコスパ。',
    scores: {
      childcare: 86,
      park: 84,
      disaster: 78,
      crime: 82,
      transit: 90,
      shopping: 84,
      medical: 82,
      cost: 82,
      quietness: 78,
    },
  },
  {
    code: '13118',
    name: '荒川区',
    x: 60,
    y: 28,
    xScatter: 70,
    yScatter: 5,
    bestEmoji: '🚃',
    description: '都電荒川線が走るレトロな街並みと、日暮里再開発の利便性が融合。',
    scores: {
      childcare: 88,
      park: 82,
      disaster: 72,
      crime: 84,
      transit: 88,
      shopping: 82,
      medical: 80,
      cost: 84,
      quietness: 78,
    },
  },
  {
    code: '13119',
    name: '板橋区',
    x: 34,
    y: 20,
    xScatter: 15,
    yScatter: 2,
    bestEmoji: '🥬',
    description: '物価が安く商店街が賑わう。ファミリー層に根強い人気を誇る生活都市。',
    scores: {
      childcare: 88,
      park: 86,
      disaster: 80,
      crime: 86,
      transit: 82,
      shopping: 82,
      medical: 84,
      cost: 88,
      quietness: 82,
    },
  },
  {
    code: '13120',
    name: '練馬区',
    x: 18,
    y: 26,
    xScatter: 2,
    yScatter: 2,
    bestEmoji: '🥦',
    description: '23区最大の農地面積と公園数。緑豊かで静かな住環境と抜群のコスパ。',
    scores: {
      childcare: 92,
      park: 98,
      disaster: 86,
      crime: 90,
      transit: 80,
      shopping: 78,
      medical: 82,
      cost: 86,
      quietness: 94,
    },
  },
  {
    code: '13121',
    name: '足立区',
    x: 68,
    y: 16,
    xScatter: 88,
    yScatter: 2,
    bestEmoji: '🚲',
    description: '北千住の大発展と優れた家賃コスパ。公園・河川敷など自然が豊富。',
    scores: {
      childcare: 88,
      park: 90,
      disaster: 76,
      crime: 76,
      transit: 86,
      shopping: 84,
      medical: 80,
      cost: 95,
      quietness: 76,
    },
  },
  {
    code: '13122',
    name: '葛飾区',
    x: 80,
    y: 28,
    xScatter: 98,
    yScatter: 15,
    bestEmoji: '🎏',
    description: '柴又や亀有に代表される下町人情。子育て医療費助成など福祉が充実。',
    scores: {
      childcare: 90,
      park: 88,
      disaster: 72,
      crime: 85,
      transit: 78,
      shopping: 80,
      medical: 80,
      cost: 92,
      quietness: 82,
    },
  },
  {
    code: '13123',
    name: '江戸川区',
    x: 82,
    y: 50,
    xScatter: 98,
    yScatter: 60,
    bestEmoji: '🎡',
    description: '葛西臨海公園をはじめ広大な公園が点在。子育て世代に手厚い支援体制。',
    scores: {
      childcare: 96,
      park: 96,
      disaster: 70,
      crime: 82,
      transit: 80,
      shopping: 82,
      medical: 82,
      cost: 88,
      quietness: 84,
    },
  },
];

export default districtsData;
